### ISSUE TITLE
Issue with require file

### ISSUE THREAD

**Issue by knowledgecorner** [pimax/fb-messenger-php-example#1]
Hi,
Nice Example 
This file not included  in index.php file
echo require_once(dirname(FILE) . '/vendor/autoload.php'); nothing to display in this file just comment the return "return ComposerAutoloaderInit304c70e3a9fe78bbc8b5b092ab75ab50::getLoader();" , it will display 1 ,
how to achieve this.

**Comment by maxpinyugin** [comment]
Hi,

You are need to install SDK via composer
`composer install`

After that, autoload.php will be created and you can use an example.

Regards
