### ISSUE TITLE
Receive the Button payload

### ISSUE THREAD

**Issue by nasirkhan** [pimax/fb-messenger-php-example#10]
Can you please show me the right way to receive the payload? In your example if i send the test 'button' 3 buttons will be appeared as 'First Button', 'Second  Button', Third  Button'. But how can i receive and process the response if The 'First  Button' is pressed?

**Comment by thinklouder** [comment]
I'm Stack at this step too, did you already know how to get valaue from the selective playloads? please let me know

**Comment by maxpinyugin** [comment]
Hello
Payload responses placed in the $message['postback']['payload'].
You can see this at the lines 68-70 in index.php file this repo.
