### ISSUE TITLE
Large int facebook IDs converted to float by json_decode PHP function

### ISSUE THREAD

**Issue by gornov** [pimax/fb-messenger-php-example#2]
Hi! I suggest to use in the example index.php: 

$data = json_decode(file_get_contents("php://input"), true, 512, JSON_BIGINT_AS_STRING);

because large int facebook ID converted to float by  json_decode PHP by default

**Comment by maxpinyugin** [comment]
Hello @gornov 

Thank you for your suggestion. 
For the future please open pull-request.

Regards, Max Pinyugin
