### ISSUE TITLE
Documentation?

### ISSUE THREAD

**Issue by danmeade** [pimax/fb-messenger-php-example#24]
Is there any chance we can get some documentation here? It's a wicked starting point, but I'm tripping up on a few things so documentation would be wicked!

**Comment by wittfabian** [comment]
I will try to expand the examples in the near future.

**Comment by ngethe** [comment]
Can help with this.. let me know i have go thorough the fb documentation and think I can make a comprehensive wiki or documentation

**Comment by wittfabian** [comment]
Examples should now cover all cases!
