### ISSUE TITLE
Bot is not answering

### ISSUE THREAD

**Issue by andreshg112** [pimax/fb-messenger-php-example#26]
I configured the bot with the token and verify_token, I run the curl command and It worked (success: true)
I'm using ngrok for the make public my server. However the bot is not answering anything. I'm getting this response from the server:

GET
![captura de pantalla de 2017-03-30 14-20-49](https://cloud.githubusercontent.com/assets/15859884/24522150/41c5e3fe-1554-11e7-90a8-8fd7c840af4d.png)

POST
![captura de pantalla de 2017-03-30 14-20-58](https://cloud.githubusercontent.com/assets/15859884/24522167/4ed41c96-1554-11e7-8636-3b037809e778.png)

![captura de pantalla de 2017-03-30 14-21-01](https://cloud.githubusercontent.com/assets/15859884/24522171/521f9600-1554-11e7-8e98-f0fb6a63bffe.png)

When I do this:
`$data = json_decode(file_get_contents("php://input"), true, 512, JSON_BIGINT_AS_STRING);

    echo json_encode($data);`

I'm getting a null value:
![captura de pantalla de 2017-03-30 14-25-06](https://cloud.githubusercontent.com/assets/15859884/24522312/c8cbd610-1554-11e7-836d-4164a7af2765.png)

**Comment by wittfabian** [comment]
The code is the backend program for your bot.
The Facebook messenger uses this code as backend for your bot If you write your bot, the code creates the response.

**Comment by andreshg112** [comment]
Yeah, that's what I'm doing. With ngrok I monitor what my server is receiving, even what Messenger is sending. What you see in the images above, are the requests sent from Messenger and the answer of the server.
The step when I configure the bot is working, but when I send messages from Messenger there's no answer.

**Comment by wittfabian** [comment]
I'm trying to reproduce the example.
I guess it's due to your framework.

**Comment by andreshg112** [comment]
Ok, I will try with Heroku and comment here what happens there.

**Comment by nbaghiro** [comment]
I am having this exact same issue and using same framework (ngrok tunneling tool), let me know if you solved this

**Comment by nbaghiro** [comment]
So I found what was the problem. It was about CURL failing certificate verification. 
I added this into FbBotApp->call() function to work around the issue:

// Telling curl not to verify certs for now
curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);

**Comment by wittfabian** [comment]
This solution is not good.

**Comment by nbaghiro** [comment]
I know but it is ok for now

**Comment by wittfabian** [comment]
ok. closed!
