### ISSUE TITLE
Receipt error

### ISSUE THREAD

**Issue by soufiane-fadil** [pimax/fb-messenger-php-example#3]
Hi ,

I tried the repo , everything is fine but when you try to display : Image , Profile and Receipt nothing work.

Maybe i missed something ?

**Comment by maxpinyugin** [comment]
Hi,

Please, check caps in your request to the bot.
"Image" and "image" not same in this repo.

Regards, Max Pinyugin

**Comment by soufiane-fadil** [comment]
Hi , i checked that , that's not working , i guess that has nothing to do with uppercase or camelcase ...

Is it possible to run it in mod debug or something ?

**Comment by maxpinyugin** [comment]
Hello
SDK doesn't has debug mode now.
I will make debug mode soon.

Regards

**Comment by soufiane-fadil** [comment]
Hello , 
I've logged errors on a files and display them with "tailf log.log" command.

It can be a solution for debugging.
Regards.

**Comment by maxpinyugin** [comment]
Of course. 
Are you found a bug?

**Comment by soufiane-fadil** [comment]
Nop , still mysterious :/

**Comment by wittfabian** [comment]
Is this still relevant?

**Comment by lephanductrong** [comment]
I have the same problem.  Image , Profile and Receipt don't work.

**Comment by wittfabian** [comment]
Can you show me the error message?

**Comment by ngethe** [comment]
Uncaught Error: Class 'pimax\\Messages\\ImageMessage' not found in
Just import the file from https://github.com/pimax/fb-messenger-php/blob/master/Messages/ImageMessage.php

**Comment by ngethe** [comment]
Or just update your composer.json with this one

https://github.com/pimax/fb-messenger-php/blob/master/composer.json

**Comment by wittfabian** [comment]
solved?
