### ISSUE TITLE
set menu not working

### ISSUE THREAD

**Issue by jnepal** [pimax/fb-messenger-php-example#30]
struggling to implement persistent view. case 'set menu' doesn't work. Any Help would be appreciated @wittfabian

**Comment by wittfabian** [comment]
Any error messanges?

**Comment by jnepal** [comment]
No errors. Isn't the persistent menu expected to popup when the message received is set menu just like generic message popup when the message received is generic?

**Comment by wittfabian** [comment]
Example:
https://venturebeat.com/2017/03/02/facebook-messenger-now-offers-a-more-dynamic-persistent-menu-for-bot-developers/

**Comment by jnepal** [comment]
Any Documentation on how to use persistent menu ? I want persistent menu to popup when user sends a certain string. is that possible ? how can it be achieved ?

**Comment by wittfabian** [comment]
I thinks thats not an use Case of the persistent menu. You can use structured Message eg.

**Comment by jnepal** [comment]
I want structured Message with button with 6 elements. but it seems only 3 elements is possible at max. Any Suggestion on how can i achieve ?

**Comment by wittfabian** [comment]
Ist there any documentation about this Limit?

**Comment by jnepal** [comment]
When i tried this in one of cases. Nothing would show up. Any idea ? but works fine for only three elements
```
$bot->send(new StructuredMessage($message['sender']['id'],
            StructuredMessage::TYPE_BUTTON,
            [
                'text' => 'Choose category',
                'buttons' => [
                    new MessageButton(MessageButton::TYPE_POSTBACK, 'First button'),
                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button'),
                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Third button'),
                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Fourth button'),
                    new MessageButton(MessageButton::TYPE_POSTBACK, 'Fifth `button')`
                ]
            ]
));
```

**Comment by wittfabian** [comment]
```
new MessageButton(MessageButton::TYPE_POSTBACK, 'Fifth `button')`
```
```
 'Fifth `button')`
```
Sind die Kommas im markierten Bereich richtig gesetzt?

**Comment by wittfabian** [comment]
I found it in the documentation. A maximum of 3 buttons

**Comment by jnepal** [comment]
English please

**Comment by jnepal** [comment]
Have you integrated webview ?

**Comment by jnepal** [comment]
or quick replies ?

**Comment by wittfabian** [comment]
quick replies => yes

**Comment by jnepal** [comment]
could you show me how to use ? any documentation

**Comment by wittfabian** [comment]
You can use "Quick Replies" with most of the messenger elements.
Check:
https://github.com/pimax/fb-messenger-php/issues/93

**Comment by jnepal** [comment]
Thanks mate @wittfabian  for the support and awesome library :)

**Comment by wittfabian** [comment]
You are welcome

**Comment by wittfabian** [comment]
I have updated index.php

**Comment by wittfabian** [comment]
Standalone:
```
$bot->send(new QuickReply($message['sender']['id'], 'Your ad here!', 
        [
            new QuickReplyButton(QuickReplyButton::TYPE_TEXT, 'QR button 1', 'PAYLOAD 1'),
            new QuickReplyButton(QuickReplyButton::TYPE_TEXT, 'QR button 2', 'PAYLOAD 2'),
            new QuickReplyButton(QuickReplyButton::TYPE_TEXT, 'QR button 3', 'PAYLOAD 3'),
        ]
));
```

**Comment by jnepal** [comment]
Thank You :)

**Comment by wittfabian** [comment]
QuickReply is restricted to 11 elements

**Comment by jnepal** [comment]
How to implement List Template Structured Message @wittfabian ?

**Comment by jbshrestha** [comment]
> I found it in the documentation. A maximum of 3 buttons

Have you found any solution on how to integrate more than 3 buttons?
