### ISSUE TITLE
button POSTBACK is not working

### ISSUE THREAD

**Issue by thmohd** [pimax/fb-messenger-php-example#31]
I am not sure if this only me , when you click postback and define the playload it does not work.

anybody help me with an example?

**Comment by wittfabian** [comment]
Any error messanges?

**Comment by thmohd** [comment]
No, it just does nothing, do you have an example of menu or button that has postback action?

**Comment by wittfabian** [comment]
Just add an URL as Payload.
```
$bot->send(new StructuredMessage($message['sender']['id'],
    StructuredMessage::TYPE_BUTTON,
    [
        'text' => 'Choose category',
        'buttons' => [
            new MessageButton(MessageButton::TYPE_POSTBACK, 'First button', 'PAYLOAD 1'),
            new MessageButton(MessageButton::TYPE_POSTBACK, 'Second button', 'PAYLOAD 2'),
            new MessageButton(MessageButton::TYPE_POSTBACK, 'Third button', 'PAYLOAD 3')
        ]
    ]
));
```
https://github.com/pimax/fb-messenger-php/blob/master/Messages/MessageButton.php
https://developers.facebook.com/docs/messenger-platform/send-api-reference/postback-button

**Comment by thmohd** [comment]
My mistake, the issue was that I didn't enable the messaging_postback on facebook webhook. I went back and found that only messaging is enabled. now it's working good. 
Thanks
