### ISSUE TITLE
Sending elements inside Structured message with data from database.

### ISSUE THREAD

**Issue by tag6071** [pimax/fb-messenger-php-example#34]
How do i pull the message elements and button elements in a structured message from the database?

**Comment by wittfabian** [comment]
What kind of database? Use case? Example?

**Comment by tag6071** [comment]
```
$bot->send(new StructuredMessage($message['sender']['id'], StructuredMessage::TYPE_GENERIC, [
                         'elements' => [
                             new MessageElement("{$name}", "{$description}", "{$image}", [
                                 new MessageButton(MessageButton::TYPE_POSTBACK, 'Hello', "HELLO_PAYLOAD")
                                     ])
                             ]
                         ]
                     ));
```

I want the data in the "elements" be pulled from the database.

**Comment by wittfabian** [comment]
This has nothing to do with this API. You should make a tutorial for the database!
What kind of database do you use?

**Comment by tag6071** [comment]
Alright. Never mind MySQL though.

**Comment by wittfabian** [comment]
I can help you to implement your requirements. But I need more informations (database table structure, etc.).
