### ISSUE TITLE
Guys, you have an error in your PersistentMenu example

### ISSUE THREAD

**Issue by arsengoian** [pimax/fb-messenger-php-example#35]
It actuually killed me two hours to figure out what the issue was =( :

In your file `index.php`

you have

                        new LocalizedMenu('default', false, [
                            new MenuItem('nested', 'My Account',
                                new MenuItem('nested', 'History',
                                    new MenuItem('postback', 'History Old', 'HISTORY_OLD_PAYLOAD'),
                                    new MenuItem('postback', 'History New', 'HISTORY_NEW_PAYLOAD')
                                ),
                                new MenuItem('postback', 'Contact_Info', 'CONTACT_INFO_PAYLOAD')
                            )
                        ])

Although it must be: 
        
            new LocalizedMenu('default', false, [
                new MenuItem('nested', 'My Account', [
                    new MenuItem('nested', 'History', [
                        new MenuItem('postback', 'History Old', 'HISTORY_OLD_PAYLOAD'),
                        new MenuItem('postback', 'History New', 'HISTORY_NEW_PAYLOAD')
                    ]),
                    new MenuItem('postback', 'Contact_Info', 'CONTACT_INFO_PAYLOAD')
                ])
            ]);

This was actually very confusing and hard to notice, please fix this

**Comment by wittfabian** [comment]
Please use the next time a clear title.

**Comment by wittfabian** [comment]
fixed
