### ISSUE TITLE
MessageButton Questions

### ISSUE THREAD

**Issue by maxpoon6218** [pimax/fb-messenger-php-example#41]
Hi, 

I am new in this project.

1)
I am using this code and want to change the description "Share". No matter what I did, the "wording" is not changed.  Can anyone suggest how can I change it ??    Thanks.

new MessageButton(MessageButton::TYPE_SHARE, 'Share'),

2)
my coding is working fine for less than 3 MessageButton. When I created 4 MessageButton, the respond seems stopped.  is there any limitation for the numbers of MessageButton?   Please advise  Thanks

**Comment by wittfabian** [comment]
https://developers.facebook.com/docs/messenger-platform/send-api-reference/button-template?locale=en_US

**Button Template:**

> Set of 1-3 buttons that appear as call-to-actions

**Comment by wittfabian** [comment]
**Share Button**
Fields: type & share_contents

I think the title feature is deprecated!

https://developers.facebook.com/docs/messenger-platform/send-api-reference/share-button

**Comment by wittfabian** [comment]
Solved?

**Comment by maxpoon6218** [comment]
still trying... >_<

**Comment by kamal-sanjeewa** [comment]
You can only use upto 3 buttons in Structured message. It is facebook limitation. Maximum of 1 button and only url button type supported when sharing via beginShareFlow(). Maximum of 3 buttons are allowed when sending via Send API.

**Comment by maxpoon6218** [comment]
_Share Button
Fields: type & share_contents
I think the title feature is deprecated!_

I think you are not answering my question, right?

**Comment by wittfabian** [comment]
The answer: Changing the text is not possible.

**Comment by wittfabian** [comment]
Solved?

**Comment by wittfabian** [comment]
Closed. No answer!
