### ISSUE TITLE
Can you show us an example how i can send a message depending by last 2-3 replies ?

### ISSUE THREAD

**Issue by yourchoice** [pimax/fb-messenger-php-example#45]
Can you show us an example how i can send a message depending by last 2-3 replies ?

I want to try something like here: https://www.messenger.com/t/recipidea

Example - scenario: 

> 1)
>     Page: "So tell me, what do you have in your fridge ?"
>     Reply: "milk"
> 2)
>     Page: "What else ?"
>     Reply: "banana"
> 3)
>     Page: "Hmmm milk and banana that looks yummy 😋. Let me think a minute ... " ... And bellow show recipes...

Practicaly in the step 3) exists replies from 1) and 2). I would like to know how can i get last 2 replies in this step.

I suppose in step 2) is colected reply from step 1) and in step 3 what is in step 2).

Have you idea how is made that ?

Thank You

**Comment by wittfabian** [comment]
This has nothing to do with this library. To do this, the data needs to be stored on the server. Or you can use services like DialogFlow.

**Comment by yourchoice** [comment]
I think can be send data using PAYLOAD. Max length 1000 chars.
