### ISSUE TITLE
'text' switch case is never executed in index.php

### ISSUE THREAD

**Issue by kapilkd13** [pimax/fb-messenger-php-example#6]
hi,
Thanks for such a wonderful API it really helped me. Now coming onto issue, the first switch case in index.php

```
    // When bot receive message from user
            if (!empty($message['message'])) {
                $command = $message['message']['text'];
```

`
which is then used in case 1
```
        // When bot receive "text"
                case 'text':
                    $bot->send(new Message($message['sender']['id'], 'This is a simple text message.'));
                    break;

``````
is never executed.
as  $message['message']['text'] returns the text message that user sent and not the message type. It should have type param which should be equal to text. But unfortunately json file sent by fb doesn't have any such parameter.
So what we can do is
1.
use  ```
  if (!empty($message['message'])) {
                $command = 'text';
``````

or 
1.  sending the message from if statement itself thus separating cases for message and postback.

**Comment by maxpinyugin** [comment]
Hello

You can change the logic in you case as you want.
`case 'text':
$bot->send(new Message($message['sender']['id'], 'This is a simple text message.'));
break;`
This code will be executed when user sent 'text' (word) and send to the bot.
This switch not for the messages type, this switch for the received text from user.
If i right understand you.

Regards.
