### ISSUE TITLE
Please show me how to get 'verify_token' & 'token' ?

### ISSUE THREAD

**Issue by anhphuong** [pimax/fb-messenger-php-example#7]
Dear Mr pimax,

I don't known how to get 'verify_token' & 'token'. Can you show me how to get them?

Thanks!

**Comment by maxpinyugin** [comment]
Hello
Please, read my article "How to Develop an IM Bot for Facebook Messenger" here: https://dzone.com/articles/how-to-develop-an-im-bot-for-facebook-messenger
You can find solution there.

Regards
