### ISSUE TITLE
unable to handle button click via payload

### ISSUE THREAD

**Issue by avinashseth** [pimax/fb-messenger-php-example#8]
First of all, i'm greatfull for what you have done, it feels great when people still writing things via php rather than getting fancy with nodejs, secondly, i'm trying to capture button payload but unable to do so, it shows bot is typing and then nothing happens, is there something i'm missing, or functionality yet to be added ?
**i'm copy and pasted your code**

**Comment by avinashseth** [comment]
**How to handle payload?**

First of all get the payload value 

I prefer without foreach and switch statement

`$special_command = $input['entry'][0]['messaging'][0]['postback']['payload'];`

now do something like this

`
if(!empty($special_command)) {
             $bot->send(new Message($sender, 'You said ' . $special_command));
            // or
           if($special_command === 'unique_payload_text_for_button_a') {
    // do the required
} else if($special_command === 'unique_payload_text_for_button_b') {
    // do the required
}  else if($special_command === 'unique_payload_text_for_button_c') {
    // do the required
}
}
`

I guess i missed the doc and here how you have to set the payload text

`
$bot->send(new StructuredMessage($message['sender']['id'],
                        StructuredMessage::TYPE_BUTTON,
                        [
                            'text' => 'Choose category',
                            'buttons' => [
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'A Button','unique_payload_text_for_button_a'),
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'B button','unique_payload_text_for_button_b'),
                                new MessageButton(MessageButton::TYPE_POSTBACK, 'unique_payload_text_for_button_c')
                            ]
                        ]
                    ));
`

*\* here is how you have to handle them **

`
// from above

`

**what is payload**
payload is just like html id, works same, nothing special but has to be unique for every button or where ever you are using

hope this helps anyone who had this issue, i learned this in 3 days so you don't have to :)

**sorry for the formatting issue**

**Comment by vetrivelbright** [comment]
hi can you post full code using php? last 2 days i am searching i am not able find working code.
my stackoverflow link
 https://stackoverflow.com/questions/44364061/how-to-get-postback-button-value-in-the-callback-url-in-facebook-messenger-bot

**Comment by wittfabian** [comment]
Open a new issue with an detailed problem description!
